# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mistydew
slogan: ソルト：無理は一番の、退屈しのぎだ。
resume: "/resume.html"
email: mistydew@qq.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; 2018 mistydew. Powered by Jekyll. Hosted with ❤ by GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mistydew.github.io" # the base hostname & protocol for your site
twitter_username: _mistydew_
github_username:  mistydew
feed: "http://feeds.feedburner.com/mistydew"

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
paginate: 07
paginate_path: "/page/:num"

# Links
permalink: /:year/:month/:day/:title
